# Практика 6. Описова статистика

**Студент:** Nazar Pryimachuk  
**Група:** IT-42  
**Варіант:** 7  
**Місто:** Івано-Франківськ  
**Регіон:** Захід

In [26]:
import pandas as pd

In [27]:
humidity = pd.Series(
    [86, 84, 81, 75, 70, 67, 65, 67, 72, 78, 83, 87],
    name="Вологість"
)

humidity.describe()

count    12.000000
mean     76.250000
std       7.967263
min      65.000000
25%      69.250000
50%      76.500000
75%      83.250000
max      87.000000
Name: Вологість, dtype: float64

### Пояснення результатів `.describe()`

- `count` — кількість спостережень, у нашому випадку 12 місяців.
- `mean` — середнє арифметичне значення вологості.
- `std` — стандартне відхилення, міра розсіювання даних відносно середнього.
- `min` — мінімальне значення.
- `25%` — перший квартиль Q1.
- `50%` — медіана, або другий квартиль Q2.
- `75%` — третій квартиль Q3.
- `max` — максимальне значення.

Розмах визначається як `max - min`, а міжквартильний розмах IQR — як `Q3 - Q1`.

In [28]:
minimum = humidity.min()
maximum = humidity.max()

rozmakh = maximum - minimum

variance_ddof1 = humidity.var(ddof=1)
variance_ddof0 = humidity.var(ddof=0)

std = humidity.std(ddof=1)

q1 = humidity.quantile(0.25)
q3 = humidity.quantile(0.75)

iqr = q3 - q1

mean = humidity.mean()
cv = std / mean * 100

print("Мінімум:", minimum)
print("Максимум:", maximum)
print("Розмах:", rozmakh)
print("Дисперсія ddof=1:", variance_ddof1)
print("Дисперсія ddof=0:", variance_ddof0)
print("Стандартне відхилення:", std)
print("Q1:", q1)
print("Q3:", q3)
print("IQR:", iqr)
print("Середнє:", mean)
print("Коефіцієнт варіації:", cv, "%")

Мінімум: 65
Максимум: 87
Розмах: 22
Дисперсія ddof=1: 63.47727272727273
Дисперсія ddof=0: 58.1875
Стандартне відхилення: 7.967262561712945
Q1: 69.25
Q3: 83.25
IQR: 14.0
Середнє: 76.25
Коефіцієнт варіації: 10.448868933394026 %


In [29]:
description = humidity.describe()

print("Q1 з describe():", description["25%"])
print("Q1 вручну:", q1)

print("Q3 з describe():", description["75%"])
print("Q3 вручну:", q3)

print("Q1 збігається:", description["25%"] == q1)
print("Q3 збігається:", description["75%"] == q3)

Q1 з describe(): 69.25
Q1 вручну: 69.25
Q3 з describe(): 83.25
Q3 вручну: 83.25
Q1 збігається: True
Q3 збігається: True


In [30]:
description = humidity.describe()

print("Q1 з describe():", description["25%"])
print("Q1 вручну:", q1)

print("Q3 з describe():", description["75%"])
print("Q3 вручну:", q3)

print("Q1 збігається:", description["25%"] == q1)
print("Q3 збігається:", description["75%"] == q3)

Q1 з describe(): 69.25
Q1 вручну: 69.25
Q3 з describe(): 83.25
Q3 вручну: 83.25
Q1 збігається: True
Q3 збігається: True


In [31]:
data = {
    "Місто": [
        "Київ", "Львів", "Одеса", "Харків", "Дніпро",
        "Чернігів", "Івано-Франківськ", "Полтава", "Суми", "Ужгород"
    ],
    "Регіон": [
        "Центр", "Захід", "Південь", "Схід", "Схід",
        "Центр", "Захід", "Центр", "Схід", "Захід"
    ],
    "Січ": [84, 85, 82, 83, 82, 85, 86, 84, 85, 84],
    "Лют": [82, 83, 80, 80, 79, 83, 84, 81, 82, 82],
    "Бер": [78, 80, 78, 75, 74, 79, 81, 76, 77, 79],
    "Кві": [70, 73, 74, 68, 67, 71, 75, 69, 70, 73],
    "Тра": [65, 68, 71, 62, 61, 66, 70, 63, 64, 68],
    "Чер": [63, 65, 69, 60, 59, 63, 67, 61, 62, 66],
    "Лип": [61, 63, 67, 58, 57, 59, 65, 59, 60, 64],
    "Сер": [63, 65, 68, 60, 59, 63, 67, 61, 62, 66],
    "Вер": [68, 70, 72, 66, 65, 69, 72, 67, 68, 71],
    "Жов": [75, 77, 76, 73, 72, 76, 78, 74, 75, 77],
    "Лис": [81, 82, 80, 79, 78, 82, 83, 82, 81, 82],
    "Гру": [85, 86, 83, 84, 83, 86, 87, 85, 86, 85]
}

df = pd.DataFrame(data)

df

,Місто,Регіон,Січ,Лют,Бер,Кві,Тра,Чер,Лип,Сер,Вер,Жов,Лис,Гру
0,Київ,Центр,84,82,78,70,65,63,61,63,68,75,81,85
1,Львів,Захід,85,83,80,73,68,65,63,65,70,77,82,86
2,Одеса,Південь,82,80,78,74,71,69,67,68,72,76,80,83
3,Харків,Схід,83,80,75,68,62,60,58,60,66,73,79,84
4,Дніпро,Схід,82,79,74,67,61,59,57,59,65,72,78,83
5,Чернігів,Центр,85,83,79,71,66,63,59,63,69,76,82,86
6,Івано-Франківськ,Захід,86,84,81,75,70,67,65,67,72,78,83,87
7,Полтава,Центр,84,81,76,69,63,61,59,61,67,74,82,85
8,Суми,Схід,85,82,77,70,64,62,60,62,68,75,81,86
9,Ужгород,Захід,84,82,79,73,68,66,64,66,71,77,82,85


In [32]:
months = [
    "Січ", "Лют", "Бер", "Кві", "Тра", "Чер",
    "Лип", "Сер", "Вер", "Жов", "Лис", "Гру"
]

df["Середня річна вологість"] = df[months].mean(axis=1)

df

,Місто,Регіон,Січ,Лют,Бер,Кві,Тра,Чер,Лип,Сер,Вер,Жов,Лис,Гру,Середня річна вологість
0,Київ,Центр,84,82,78,70,65,63,61,63,68,75,81,85,72.916667
1,Львів,Захід,85,83,80,73,68,65,63,65,70,77,82,86,74.750000
2,Одеса,Південь,82,80,78,74,71,69,67,68,72,76,80,83,75.000000
3,Харків,Схід,83,80,75,68,62,60,58,60,66,73,79,84,70.666667
4,Дніпро,Схід,82,79,74,67,61,59,57,59,65,72,78,83,69.666667
5,Чернігів,Центр,85,83,79,71,66,63,59,63,69,76,82,86,73.500000
6,Івано-Франківськ,Захід,86,84,81,75,70,67,65,67,72,78,83,87,76.250000
7,Полтава,Центр,84,81,76,69,63,61,59,61,67,74,82,85,71.833333
8,Суми,Схід,85,82,77,70,64,62,60,62,68,75,81,86,72.666667
9,Ужгород,Захід,84,82,79,73,68,66,64,66,71,77,82,85,74.750000


In [33]:
west = df[df["Регіон"] == "Захід"]["Середня річна вологість"]

west.describe()

count     3.000000
mean     75.250000
std       0.866025
min      74.750000
25%      74.750000
50%      74.750000
75%      75.500000
max      76.250000
Name: Середня річна вологість, dtype: float64

In [34]:
center = df[df["Регіон"] == "Центр"]["Середня річна вологість"]

center.describe()

count     3.000000
mean     72.750000
std       0.845741
min      71.833333
25%      72.375000
50%      72.916667
75%      73.208333
max      73.500000
Name: Середня річна вологість, dtype: float64

In [35]:
cv_west = west.std() / west.mean() * 100
cv_center = center.std() / center.mean() * 100

print("CV Захід:", cv_west, "%")
print("CV Центр:", cv_center, "%")

CV Захід: 1.1508643239660312 %
CV Центр: 1.162530534374829 %


In [37]:
mean = 76.25
median = 76.50
mean_value = humidity.mean()
median_value = humidity.median()

print("Середнє:", mean_value)
print("Медіана:", median_value)
print("Різниця:", abs(mean_value - median_value))

Середнє: 76.25
Медіана: 76.5
Різниця: 0.25


In [38]:
ivano_frankivsk = df[df["Місто"] == "Івано-Франківськ"]

kharkiv = df[df["Місто"] == "Харків"]

ivano_values = ivano_frankivsk[months].iloc[0]
kharkiv_values = kharkiv[months].iloc[0]

ivano_cv = ivano_values.std() / ivano_values.mean() * 100
kharkiv_cv = kharkiv_values.std() / kharkiv_values.mean() * 100

print("Івано-Франківськ:")
print("Середнє:", ivano_values.mean())
print("Std:", ivano_values.std())
print("CV:", ivano_cv, "%")

print("\nХарків:")
print("Середнє:", kharkiv_values.mean())
print("Std:", kharkiv_values.std())
print("CV:", kharkiv_cv, "%")

Івано-Франківськ:
Середнє: 76.25
Std: 7.967262561712945
CV: 10.448868933394026 %

Харків:
Середнє: 70.66666666666667
Std: 9.547330263037681
CV: 13.510373013732565 %


In [39]:
print("Івано-Франківськ")
print(ivano_values.describe())

print("\nХарків")
print(kharkiv_values.describe())

Івано-Франківськ
count    12.000000
mean     76.250000
std       7.967263
min      65.000000
25%      69.250000
50%      76.500000
75%      83.250000
max      87.000000
Name: 6, dtype: float64

Харків
count    12.000000
mean     70.666667
std       9.547330
min      58.000000
25%      61.500000
50%      70.500000
75%      79.250000
max      84.000000
Name: 3, dtype: float64


## Відповіді на контрольні питання

### 1. Які міри розсіювання стоять за рядками `.describe()`?

`std` — стандартне відхилення, яке характеризує розсіювання значень відносно середнього.

`25%` і `75%` — перший та третій квартилі. За ними визначається міжквартильний розмах IQR:

`IQR = Q3 - Q1`.

`min` і `max` — мінімальне та максимальне значення. За ними можна визначити загальний розмах:

`Range = max - min`.

### 2. Чому заповнення пропуску середнім штучно зменшує std?

Якщо пропущене значення замінити середнім, воно буде розташоване точно в центрі розподілу та не матиме відхилення від середнього. Наприклад, для значень `10, 20, 30` середнє дорівнює `20`. Якщо замінити пропуск середнім, отримуємо додаткове значення `20`. Воно не збільшує суму квадратів відхилень, тому відносне розсіювання набору зменшується. Таким чином, таке заповнення може штучно зменшувати `std`.

### 3. Чому не можна безпосередньо порівнювати std груп різного масштабу?

Стандартне відхилення є абсолютною мірою розсіювання. Якщо дві групи мають різні середні значення або різний масштаб, однаковий або більший `std` не обов'язково означає більшу відносну варіативність. Для коректного порівняння використовують коефіцієнт варіації:

`CV = std / mean * 100%`.

Він показує розсіювання відносно середнього значення.

### 4. Чи симетричний розподіл власних даних?

Для Івано-Франківська середнє значення становить 76.25%, а медіана — 76.50%. Вони дуже близькі, тому розподіл є близьким до симетричного.

Через відсутність значної різниці між середнім і медіаною середнє арифметичне є репрезентативною мірою положення для цих даних. Медіана також добре характеризує центр розподілу.